version: "3.8"

services:
  client:
    container_name: frontend-aic
    image: frontend-aic
    build:
      context: ./client
      target: development
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/app/client/src
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_ENDPOINT=http:/localhost:8000
      - REACT_APP_OCR_VM_IP=localhost
    restart: always

  metadata:
    container_name: service-metadata
    image: service-metadata
    build:
      context: ./metadata
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always

  ocr:
    container_name: service-ocr
    image: service-ocr
    build:
      context: ./AIC-OCR-search
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
