version: "3.8"

services:
  client:
    container_name: frontend-aic
    image: frontend-aic
    build:
      context: ./services/client
      target: development
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/app/client/src
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_ENDPOINT=http:/localhost:8000
      - REACT_APP_OCR_VM_IP=localhost
    restart: always

  metadata:
    container_name: service-metadata
    image: service-metadata
    build:
      context: ./services/metadata
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always

  clip-itr:
    container_name: service-clip
    image: service-clip
    build:
      context: ./services/clip-itr
      dockerfile: Dockerfile
    ports:
      - 8080:7860
    restart: always

  beit3-itr:
    container_name: service-beit3
    image: service-beit3
    build:
      context: ./services/beit3-itr
      dockerfile: Dockerfile
    ports:
      - 8081:7860
    restart: always

  clip2video-vtr:
    container_name: service-clip2video
    image: service-clip2video
    build:
      context: ./services/clip2video-vtr
      dockerfile: Dockerfile
    ports:
      - 8082:7860
    restart: always

  object-search:
    container_name: service-object
    image: service-object
    build:
      context: ./services/AIC-Object-search
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    restart: always

  ocr:
    container_name: service-ocr
    image: service-ocr
    build:
      context: ./services/AIC-OCR-search
      dockerfile: Dockerfile
    ports:
      - 8084:8080
    restart: always
